/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockCountRouteImport } from './routes/stock-count'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ContractsIdRouteImport } from './routes/contracts_.$id'
import { Route as CustomersIdRouteImport } from './routes/customers_.$id'
import { Route as ProductsIdRouteImport } from './routes/products_.$id'
import { Route as PurchasesIdRouteImport } from './routes/purchases.$id'
import { Route as PurchasesNewRouteImport } from './routes/purchases.new'
import { Route as SalesIdRouteImport } from './routes/sales.$id'
import { Route as SalesNewRouteImport } from './routes/sales.new'
import { Route as SalesNewInstallmentRouteImport } from './routes/sales.new-installment'
import { Route as SuppliersIdRouteImport } from './routes/suppliers_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockCountRoute = StockCountRouteImport.update({
  id: '/stock-count',
  path: '/stock-count',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIdRoute = ContractsIdRouteImport.update({
  id: '/contracts_/$id',
  path: '/contracts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers_/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesIdRoute = PurchasesIdRouteImport.update({
  id: '/purchases/$id',
  path: '/purchases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesNewRoute = PurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIdRoute = SalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesNewInstallmentRoute = SalesNewInstallmentRouteImport.update({
  id: '/sales/new-installment',
  path: '/sales/new-installment',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers_/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/audit': typeof AuditRoute
  '/collections': typeof CollectionsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/stock-count': typeof StockCountRoute
  '/suppliers': typeof SuppliersRoute
  '/treasury': typeof TreasuryRoute
  '/users': typeof UsersRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/purchases/$id': typeof PurchasesIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/new-installment': typeof SalesNewInstallmentRoute
  '/suppliers/$id': typeof SuppliersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/audit': typeof AuditRoute
  '/collections': typeof CollectionsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/stock-count': typeof StockCountRoute
  '/suppliers': typeof SuppliersRoute
  '/treasury': typeof TreasuryRoute
  '/users': typeof UsersRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/purchases/$id': typeof PurchasesIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/new-installment': typeof SalesNewInstallmentRoute
  '/suppliers/$id': typeof SuppliersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRoute
  '/audit': typeof AuditRoute
  '/collections': typeof CollectionsRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/stock-count': typeof StockCountRoute
  '/suppliers': typeof SuppliersRoute
  '/treasury': typeof TreasuryRoute
  '/users': typeof UsersRoute
  '/contracts_/$id': typeof ContractsIdRoute
  '/customers_/$id': typeof CustomersIdRoute
  '/products_/$id': typeof ProductsIdRoute
  '/purchases/$id': typeof PurchasesIdRoute
  '/purchases/new': typeof PurchasesNewRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/sales/new-installment': typeof SalesNewInstallmentRoute
  '/suppliers_/$id': typeof SuppliersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/audit'
    | '/collections'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/login'
    | '/products'
    | '/settings'
    | '/stock-count'
    | '/suppliers'
    | '/treasury'
    | '/users'
    | '/contracts/$id'
    | '/customers/$id'
    | '/products/$id'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/new-installment'
    | '/suppliers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting'
    | '/audit'
    | '/collections'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/login'
    | '/products'
    | '/settings'
    | '/stock-count'
    | '/suppliers'
    | '/treasury'
    | '/users'
    | '/contracts/$id'
    | '/customers/$id'
    | '/products/$id'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/new-installment'
    | '/suppliers/$id'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/audit'
    | '/collections'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/login'
    | '/products'
    | '/settings'
    | '/stock-count'
    | '/suppliers'
    | '/treasury'
    | '/users'
    | '/contracts_/$id'
    | '/customers_/$id'
    | '/products_/$id'
    | '/purchases/$id'
    | '/purchases/new'
    | '/sales/$id'
    | '/sales/new'
    | '/sales/new-installment'
    | '/suppliers_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRoute
  AuditRoute: typeof AuditRoute
  CollectionsRoute: typeof CollectionsRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  ExpensesRoute: typeof ExpensesRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  StockCountRoute: typeof StockCountRoute
  SuppliersRoute: typeof SuppliersRoute
  TreasuryRoute: typeof TreasuryRoute
  UsersRoute: typeof UsersRoute
  ContractsIdRoute: typeof ContractsIdRoute
  CustomersIdRoute: typeof CustomersIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  PurchasesIdRoute: typeof PurchasesIdRoute
  PurchasesNewRoute: typeof PurchasesNewRoute
  SalesIdRoute: typeof SalesIdRoute
  SalesNewRoute: typeof SalesNewRoute
  SalesNewInstallmentRoute: typeof SalesNewInstallmentRoute
  SuppliersIdRoute: typeof SuppliersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-count': {
      id: '/stock-count'
      path: '/stock-count'
      fullPath: '/stock-count'
      preLoaderRoute: typeof StockCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts_/$id': {
      id: '/contracts_/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers_/$id': {
      id: '/customers_/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$id': {
      id: '/products_/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/$id': {
      id: '/purchases/$id'
      path: '/purchases/$id'
      fullPath: '/purchases/$id'
      preLoaderRoute: typeof PurchasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases/new': {
      id: '/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof PurchasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$id': {
      id: '/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof SalesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/new-installment': {
      id: '/sales/new-installment'
      path: '/sales/new-installment'
      fullPath: '/sales/new-installment'
      preLoaderRoute: typeof SalesNewInstallmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers_/$id': {
      id: '/suppliers_/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRoute,
  AuditRoute: AuditRoute,
  CollectionsRoute: CollectionsRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  ExpensesRoute: ExpensesRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  StockCountRoute: StockCountRoute,
  SuppliersRoute: SuppliersRoute,
  TreasuryRoute: TreasuryRoute,
  UsersRoute: UsersRoute,
  ContractsIdRoute: ContractsIdRoute,
  CustomersIdRoute: CustomersIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  PurchasesIdRoute: PurchasesIdRoute,
  PurchasesNewRoute: PurchasesNewRoute,
  SalesIdRoute: SalesIdRoute,
  SalesNewRoute: SalesNewRoute,
  SalesNewInstallmentRoute: SalesNewInstallmentRoute,
  SuppliersIdRoute: SuppliersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
