-- Extends the atomic counter mechanism from 0022_tenant_code_counters.sql to the year-prefixed
-- document numbers (INV/CNT/RCT/PUR/RET/EXC/JE-YYYY-NNNNNN) generated by nextInvoiceNumber /
-- nextInstallmentDocNumber in supabase-queries.ts. Those still used COUNT(*) + ilike — not
-- currently exploitable the way customer codes were (no single-row hard delete exists for any
-- of these tables), but a real collision under normal concurrent traffic (two simultaneous
-- sales), and it becomes exactly the same permanent-corruption bug the moment any single-row
-- delete is ever added to one of these tables. next_tenant_code_counter() already exists
-- (0022); this only backfills its counters for these six tables/columns so existing tenants'
-- numbering continues seamlessly instead of restarting at 1. The counter key is
-- `<table>:<year>` (not just `<table>`) because these numbers reset every calendar year.

insert into tenant_code_counters (tenant_id, entity, counter)
select
  tenant_id,
  'sales:' || substring(invoice_number from '-(\d{4})-\d+$'),
  max(substring(invoice_number from '-\d{4}-(\d+)$')::int)
from sales
where invoice_number ~ '-\d{4}-\d+$'
group by tenant_id, substring(invoice_number from '-(\d{4})-\d+$')
on conflict (tenant_id, entity) do update set counter = greatest(tenant_code_counters.counter, excluded.counter);

insert into tenant_code_counters (tenant_id, entity, counter)
select
  tenant_id,
  'installment_contracts:' || substring(contract_number from '-(\d{4})-\d+$'),
  max(substring(contract_number from '-\d{4}-(\d+)$')::int)
from installment_contracts
where contract_number ~ '-\d{4}-\d+$'
group by tenant_id, substring(contract_number from '-(\d{4})-\d+$')
on conflict (tenant_id, entity) do update set counter = greatest(tenant_code_counters.counter, excluded.counter);

insert into tenant_code_counters (tenant_id, entity, counter)
select
  tenant_id,
  'installment_payments:' || substring(receipt_number from '-(\d{4})-\d+$'),
  max(substring(receipt_number from '-\d{4}-(\d+)$')::int)
from installment_payments
where receipt_number ~ '-\d{4}-\d+$'
group by tenant_id, substring(receipt_number from '-(\d{4})-\d+$')
on conflict (tenant_id, entity) do update set counter = greatest(tenant_code_counters.counter, excluded.counter);

insert into tenant_code_counters (tenant_id, entity, counter)
select
  tenant_id,
  'purchases:' || substring(purchase_number from '-(\d{4})-\d+$'),
  max(substring(purchase_number from '-\d{4}-(\d+)$')::int)
from purchases
where purchase_number ~ '-\d{4}-\d+$'
group by tenant_id, substring(purchase_number from '-(\d{4})-\d+$')
on conflict (tenant_id, entity) do update set counter = greatest(tenant_code_counters.counter, excluded.counter);

insert into tenant_code_counters (tenant_id, entity, counter)
select
  tenant_id,
  'sale_returns:' || substring(return_number from '-(\d{4})-\d+$'),
  max(substring(return_number from '-\d{4}-(\d+)$')::int)
from sale_returns
where return_number ~ '-\d{4}-\d+$'
group by tenant_id, substring(return_number from '-(\d{4})-\d+$')
on conflict (tenant_id, entity) do update set counter = greatest(tenant_code_counters.counter, excluded.counter);

insert into tenant_code_counters (tenant_id, entity, counter)
select
  tenant_id,
  'exchange_transactions:' || substring(exchange_number from '-(\d{4})-\d+$'),
  max(substring(exchange_number from '-\d{4}-(\d+)$')::int)
from exchange_transactions
where exchange_number ~ '-\d{4}-\d+$'
group by tenant_id, substring(exchange_number from '-(\d{4})-\d+$')
on conflict (tenant_id, entity) do update set counter = greatest(tenant_code_counters.counter, excluded.counter);

insert into tenant_code_counters (tenant_id, entity, counter)
select
  tenant_id,
  'journal_entries:' || substring(entry_number from '-(\d{4})-\d+$'),
  max(substring(entry_number from '-\d{4}-(\d+)$')::int)
from journal_entries
where entry_number ~ '-\d{4}-\d+$'
group by tenant_id, substring(entry_number from '-(\d{4})-\d+$')
on conflict (tenant_id, entity) do update set counter = greatest(tenant_code_counters.counter, excluded.counter);
